"""Add CRM, Reports, Analytics and Teams models

Revision ID: 1106985f0c5b
Revises: 1da2960a1a16
Create Date: 2025-10-30 11:44:54.031752

"""
from alembic import op
import sqlalchemy as sa
from models import * # NOUVEAU : Importer tous les modèles pour qu'Alembic les détecte


# revision identifiers, used by Alembic.
revision = '1106985f0c5b'
down_revision = '1da2960a1a16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agency_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('leader_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agency.id'], ),
    sa.ForeignKeyConstraint(['leader_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_teams_agency_id'), ['agency_id'], unique=False)

    op.create_table('sales_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agency_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('total_sales', sa.Integer(), nullable=True),
    sa.Column('total_revenue', sa.Integer(), nullable=True),
    sa.Column('average_sale', sa.Integer(), nullable=True),
    sa.Column('trip_count', sa.Integer(), nullable=True),
    sa.Column('detailed_data', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agency.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_reports_agency_id'), ['agency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_reports_period_end'), ['period_end'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_reports_period_start'), ['period_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_reports_user_id'), ['user_id'], unique=False)

    op.create_table('client_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('interaction_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_interactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_interactions_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_interactions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_interactions_interaction_type'), ['interaction_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_interactions_user_id'), ['user_id'], unique=False)

    # Client columns already exist, skip
    # with op.batch_alter_table('client', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('client_type', sa.String(length=20), nullable=True))
    #     batch_op.add_column(sa.Column('total_purchases', sa.Integer(), nullable=True))
    #     batch_op.add_column(sa.Column('total_revenue', sa.Integer(), nullable=True))
    #     batch_op.add_column(sa.Column('last_purchase_date', sa.DateTime(), nullable=True))
    #     batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
    #     batch_op.add_column(sa.Column('source', sa.String(length=50), nullable=True))
    #     batch_op.add_column(sa.Column('birthday', sa.Date(), nullable=True))
    #     batch_op.add_column(sa.Column('preferences', sa.JSON(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sales_target', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('commission_rate', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_team_leader', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('team_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_team_id_sales_teams', 'sales_teams', ['team_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_team_id_sales_teams', type_='foreignkey')
        batch_op.drop_column('team_id')
        batch_op.drop_column('is_team_leader')
        batch_op.drop_column('commission_rate')
        batch_op.drop_column('sales_target')

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('preferences')
        batch_op.drop_column('birthday')
        batch_op.drop_column('source')
        batch_op.drop_column('notes')
        batch_op.drop_column('last_purchase_date')
        batch_op.drop_column('total_revenue')
        batch_op.drop_column('total_purchases')
        batch_op.drop_column('client_type')

    with op.batch_alter_table('client_interactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_interactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_client_interactions_interaction_type'))
        batch_op.drop_index(batch_op.f('ix_client_interactions_created_at'))
        batch_op.drop_index(batch_op.f('ix_client_interactions_client_id'))

    op.drop_table('client_interactions')
    with op.batch_alter_table('sales_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_reports_user_id'))
        batch_op.drop_index(batch_op.f('ix_sales_reports_period_start'))
        batch_op.drop_index(batch_op.f('ix_sales_reports_period_end'))
        batch_op.drop_index(batch_op.f('ix_sales_reports_agency_id'))

    op.drop_table('sales_reports')
    with op.batch_alter_table('sales_teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_teams_agency_id'))

    op.drop_table('sales_teams')
    # ### end Alembic commands ###
