"""Add manual payment fields to Trip

Revision ID: 17571a263473
Revises: c5654a8c8ec6
Create Date: 2025-10-15 10:42:29.469830

"""
from alembic import op
import sqlalchemy as sa
from models import * # NOUVEAU : Importer tous les modèles pour qu'Alembic les détecte


# revision identifiers, used by Alembic.
revision = '17571a263473'
down_revision = 'c5654a8c8ec6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('down_payment_status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.drop_column('down_payment_status')
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
