"""Add secondary_color to Agency model

Revision ID: 1da2960a1a16
Revises: 643e836dd01a
Create Date: 2025-10-16 17:36:43.714558

"""
from alembic import op
import sqlalchemy as sa
from models import * # NOUVEAU : Importer tous les modèles pour qu'Alembic les détecte


# revision identifiers, used by Alembic.
revision = '1da2960a1a16'
down_revision = '643e836dd01a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agency', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secondary_color', sa.String(length=7), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agency', schema=None) as batch_op:
        batch_op.drop_column('secondary_color')

    # ### end Alembic commands ###
