"""Add email template field to Agency

Revision ID: 79086f1b2d7b
Revises: 17571a263473
Create Date: 2025-10-15 10:44:02.432646

"""
from alembic import op
import sqlalchemy as sa
from models import * # NOUVEAU : Importer tous les modèles pour qu'Alembic les détecte


# revision identifiers, used by Alembic.
revision = '79086f1b2d7b'
down_revision = '17571a263473'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agency', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manual_payment_email_template', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agency', schema=None) as batch_op:
        batch_op.drop_column('manual_payment_email_template')

    # ### end Alembic commands ###
