"""Add TripNote model

Revision ID: 8e2fc4b3e373
Revises: 9f1825b27cb4
Create Date: 2025-10-15 10:20:41.267065

"""
from alembic import op
import sqlalchemy as sa
from models import * # NOUVEAU : Importer tous les modèles pour qu'Alembic les détecte


# revision identifiers, used by Alembic.
revision = '8e2fc4b3e373'
down_revision = '9f1825b27cb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trip_note', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trip_note_trip_id'), ['trip_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trip_note_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_note', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trip_note_user_id'))
        batch_op.drop_index(batch_op.f('ix_trip_note_trip_id'))

    op.drop_table('trip_note')
    # ### end Alembic commands ###
