"""Add transport fields to Trip model

Revision ID: 9f1825b27cb4
Revises: ab4f62f98ab1
Create Date: 2025-10-14 17:40:31.600067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f1825b27cb4'
down_revision = 'ab4f62f98ab1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transport_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('bus_departure_address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('travel_duration_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('departure_time', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('return_time', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.drop_column('return_time')
        batch_op.drop_column('departure_time')
        batch_op.drop_column('travel_duration_minutes')
        batch_op.drop_column('bus_departure_address')
        batch_op.drop_column('transport_type')

    # ### end Alembic commands ###
